### ISSUE TITLE
Implement an actual WorkQueue for the U2FManager

### ISSUE THREAD

**Issue by ttaubert** [jcjones/u2f-hid-rs#11]
The first version of the U2FManager was added to provide the right API. Because PlatformManager::cancel() can block however, we need implement a work queue that spawns a thread and has `register`, `sign`, and `cancel` as work items. These corresponds to API calls from PBackground.

**Comment by jcjones** [comment]
Fixed in eb312fa36eb3f881fb8a9e820e0f9eca2583ec46
