### ISSUE TITLE
Using TouchID as a security key - MacOS

### ISSUE THREAD

**Issue by kshah00** [jcjones/u2f-hid-rs#257]
Hey guys, 
It would be great if Firefox on macOS supported TouchID for viewing passwords, loging in and also as security keys (like on github).

**Comment by jschanck** [comment]
Agreed! This is a frequently requested feature, and I'm happy to say that we are working on it. I'm going to close this issue as we are tracking the feature in Bugzilla [Bug 1536482](https://bugzilla.mozilla.org/show_bug.cgi?id=1536482).
