### ISSUE TITLE
Select a reasonable default pin protocol when `pinUvAuthProtocols` is absent from GetInfo response

### ISSUE THREAD

**Issue by jschanck** [jcjones/u2f-hid-rs#274]
In [Bug 1836722](https://bugzilla.mozilla.org/show_bug.cgi?id=1836722) we have a user reporting that WebAuthn transactions with a WearAuthn token abort immediately with `[ERROR authenticator::statemachine] Error when determining pinAuth: HIDError(Command(UnsupportedPinProtocol))`. This seems to be because WearAuthn doesn't report `pinUvAuthProtocols` in its [`GetInfo` response](https://github.com/fmeum/WearAuthn/blob/35b2e913a433621ab67d065aae48fbe1bfb121fd/authenticator/src/main/java/me/henneke/wearauthn/fido/ctap2/Authenticator.kt#L560-L605).

The spec is not very clear about what we should do here. But my interpretation is:
1) For CTAP 2.0 devices we should use protocol 1, because protocol 2 wasn't defined for 2.0.
2) For CTAP 2.1 we should use protocol 2, because protocol 2 is mandatory-to-implement in 2.1.

We should also wrap the `pin_protocols` entry in our `AuthenticatoInfo` struct with `Option`, as there's a clause in 2.1 that the device MUST NOT return an empty list.

**Comment by msirringhaus** [comment]
The spec seems to be almost deliberately unclear here :sweat_smile: 

For CTAP 2.1, the spec says:
> [9. Mandatory features](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#mandatory-features)
>
> Authenticators that include FIDO_2_1 in [versions](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#getinfo-versions):
> ...
> 6. MUST include an array element with the value 2 in the [authenticatorGetInfo](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#authenticatorGetInfo) response’s [pinUvAuthProtocols](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#getinfo-pinuvauthprotocols) member (i.e. support [PIN/UV auth protocol two](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#pinProto2)) if it includes any values at all.

So, I think I agree. We should determine the protocol version based on the supported CTAP-level, if none is returned.
