### ISSUE TITLE
AppId Extension is broken again for FIDO2 security keys in Firefox 122

### ISSUE THREAD

**Issue by andreydanil** [jcjones/u2f-hid-rs#331]
The problem is when an AppId extension is provided for a FIDO2 security key, the user can enter the FIDO2 PIN, but then nothing happens after a user enters a PIN and clicks submit - the browser no longer talks to the authenticator. This is only a problem starting with the 122 release.

Issue:
<img width="802" alt="image" src="https://github.com/mozilla/authenticator-rs/assets/5439988/d4c65fee-4e41-4717-aea9-273fe8aacb80">

It looks like this PIN prompt is no longer valid since Firefox was switched to the new popup mechanism.

I see a few major changes: to how the [preflights in CTAP2 logic](https://github.com/mozilla/authenticator-rs/commit/32f8e144eac287ec9ecb7b54c707e7c5bb32fbb0) and a [Rework support for AppId extension](https://github.com/mozilla/authenticator-rs/commit/d512ad9b5deb88edce20eca002659e469e4f8341).

It appears that starting Firefox 122, the default popup is the Apple/Safari one, however, when an AppId extension is provided, the old popup occurs and nothing happens after entering a PIN.
 
<img width="499" alt="image" src="https://github.com/mozilla/authenticator-rs/assets/5439988/8509fcad-16c8-4426-8c49-bcc149ac29b6">

**Comment by msirringhaus** [comment]
Could you try this using Linux? I have a feeling that this may have nothing to do with `authenticator-rs`, but with the usage of the system dialogs for passkeys/security keys on Macs specifically.

**Comment by jschanck** [comment]
Testing on macOS with `security.webauthn.enable_macos_passkeys = false` would be sufficient to rule out an authenticator-rs regression.

**Comment by andreydanil** [comment]
@msirringhaus, ~~this is an issue on Linux as well~~. Linux is working and not broken as of FF122,

@jschanck setting `security.webauthn.enable_macos_passkeys` to `false` makes the security key to respond to the challenge after entering the FIDO2 token PIN  (using the AppID extension). Thank you for the suggestion!

This does unblock users in an environment where U2F and FIDO2 security keys are registered, however is it possible to make the passkeys not interfere with WebAuthn as in FF121?

**Comment by jschanck** [comment]
That doesn't make sense to me. Setting `security.webauthn.enable_macos_passkeys` to `false` makes macOS use authenticator-rs by default, which should align its behavior with Linux (which you say is not working). Did you also set `security.webauthn.ctap2` to false on macOS (and not on Linux)?

**Comment by andreydanil** [comment]
I see. Linux appears to be working now, I had multiple security keys plugged and one of the devices was holding on to the previous challenge.

It's an issue with MacOS only then. Using the AppId extension in Safari works with U2F and FIDO2 keys, however the FF122 version appears to be breaking the Authentication. Given that Safari works with the new popup, it appears there is a bug on the FF end, but may not be necessarily with the authenticator-rs library. Feel free to chime in.

* FF121 works with both U2F and FIDO2 keys.
* FF122 works for U2F keys, but not FIDO2 keys using the ApId extension.
* FF122 works when `security.webauthn.enable_macos_passkeys=false`.

Thanks a lot for the quick responses @jschanck and @msirringhaus!

**Comment by jschanck** [comment]
Thank you, I found the underlying issue in Firefox, and I'll post a patch shortly. It is not a regression in authenticator-rs.

**Comment by andreydanil** [comment]
@jschanck , thank you again! One request - Can this please be patched in FF122?

**Comment by jschanck** [comment]
Probably not. I'll request beta uplift for 123, but we're pretty far into the release cycle at this point.

**Comment by andreydanil** [comment]
Got it. I appreciate if the fix can come into FF123. Thanks so much!

**Comment by andreydanil** [comment]
Linking the bugzilla ticket for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1878598.
