### ISSUE TITLE
u2f_register must accept a list of already-registered key handles

### ISSUE THREAD

**Issue by jcjones** [jcjones/u2f-hid-rs#40]
Like `u2f_sign`, `u2f_register` needs to accept an exclusion list of key handles that it can attempt to use before proceeding.

This could be done by having `u2f_register` accept an array of byte arrays, or defining a function that checks a single key handle at once (`is_registered`) which can be called serially by the U2FManager.

**Comment by ttaubert** [comment]
See [https://bugzilla.mozilla.org/show_bug.cgi?id=1400668](https://bugzilla.mozilla.org/show_bug.cgi?id=1400668)

**Comment by jcjones** [comment]
Fixed in 4d965aacd74ce7b11b299ce0523f14f8180d4e74
