### ISSUE TITLE
Yubikey ping packet corruption when device is inserted during polling

### ISSUE THREAD

**Issue by madwizard-thomas** [jcjones/u2f-hid-rs#63]
I've been using my yubikey in firefox for U2F (on windows) and have noticed it almost never works if I insert the USB device after the registration/sign sequence has begun. I have tried it directly with this library and it also gives problems there with the default example (main). If the key was inserted before starting it works fine, if I insert it after starting while it's polling, it sometimes works but most of the time it will fail.

I tracked the problem down to the ping function returning different bytes than the random bytes that were sent. In fact the sequence returned is pretty much always the same. I think it may be a hardware issue with the yubikey, not with your source code and was wondering if you've come across this issue? My yubikey is a few years old (U2F firmware is 1.1.0) so it might work with newer versions.

Using a USB capture I found out that when the ping request is sent, between the request packet and response packet there is a bunch of CCID/ISO7816 commands (note that my yubikey is in U2F+CCID mode), this is probably windows checking the smartcard type. The bytes that are returned in the ping response actually seem to come from parts of earlier CCID responses, so I suspect the yubikey's memory where the ping request is stored is corrupted by these intervening packets. When the registration is done some time after initialization it works because there is no other simultaneous communication.

**Comment by ttaubert** [comment]
Thanks for reporting and thank you even more for debugging this so thoroughly!

We should have a fix soon [1] that will remove the ping call and work around the issue reported here.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=14603
