### ISSUE TITLE
Refactor U2FManager out of main.rs

### ISSUE THREAD

**Issue by jcjones** [jcjones/u2f-hid-rs#7]
U2FManager belongs somewhere other than `main.rs`.

Perhaps pull that into a `state_machine.rs` and, similarly, refactor `lib.rs`'s  u2f hid support stuff into `u2fprotocol.rs`

**Comment by ttaubert** [comment]
I used `manager.rs` instead of `state_machine.rs` because for now I think that makes more sense, most of the actual state machine lives with the platform.
